name: Build
on:
  push:
jobs:
  build:
    name: Build Project
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - { name: "Windows MSVC", os: windows-latest, cc: "cl", cxx: "cl" }
          - { name: "Ubuntu gcc", os: ubuntu-latest, cc: "clang", cxx: "clang++" }
          - { name: "MacOS clang", os: macos-latest, cc: "clang", cxx: "clang++" }
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.1

      - name: Install Conan
        run: |
          sudo apt-get install -y python3
          pip install conan

      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master
        with:
          version: 1.11.4

      - name: Build with CMake
        uses: ashutoshvarma/action-cmake-build@master
        with:
          build-dir: ${{ runner.workspace }}/build
          cc: ${{ matrix.config.cc }}
          cxx: ${{ matrix.config.cxx }}
          configure-options: -G Ninja
          build-type: Release
