name: Build
on:
  push:
jobs:
  build:
    name: Build Project
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - { name: "Ubuntu Clang", os: ubuntu-latest, cc: "clang", cxx: "clang++" }
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.1

      - name: Install Conan
        run: |
          sudo apt-get install -y python3
          pip install conan

      - name: Set up Clang
        run: |
          sudo add-apt-repository -y "deb http://apt.llvm.org/unstable/ llvm-toolchain main"
          sudo add-apt-repository -y "deb-src http://apt.llvm.org/unstable/ llvm-toolchain main"
          sudo add-apt-repository -y "deb http://apt.llvm.org/unstable/ llvm-toolchain-18 main" || true
          sudo add-apt-repository -y "deb-src http://apt.llvm.org/unstable/ llvm-toolchain-18 main" || true
          sudo apt-get update -y
          sudo apt-get install -y clang-18 clang-tools-18

      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master
        with:
          version: 1.12.1

      - name: Build with CMake
        uses: ashutoshvarma/action-cmake-build@master
        with:
          build-dir: ${{ runner.workspace }}/build
          cc: ${{ matrix.config.cc }}
          cxx: ${{ matrix.config.cxx }}
          configure-options: -G Ninja
          build-type: Release
