name: Build
on:
  push:
jobs:
  build:
    name: Build Project
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - { name: "Ubuntu Clang", os: ubuntu-latest, cc: "clang-18", cxx: "clang++-18" }
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.1

      - name: Install Conan
        run: |
          sudo apt-get install -y python3
          pip install conan

      - name: Set up Clang
        run: |
          wget -qO- https://apt.llvm.org/llvm.sh | sudo bash -s -- 18

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Build with CMake
        uses: ashutoshvarma/action-cmake-build@master
        with:
          build-dir: ${{ runner.workspace }}/build
          cc: ${{ matrix.config.cc }}
          cxx: ${{ matrix.config.cxx }}
          configure-options: -G Ninja -DCMAKE_CXX_COMPILER_CLANG_SCAN_DEPS=clang-scan-deps-18
          build-type: Release
