name: Build
on:
  push:
jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.1

      - name: Install Conan
        run: |
          sudo apt-get install -y python3
          pip install conan

      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Build Project
        run: |
          mkdir build
          cd build
          cmake -G Ninja -D CMAKE_BUILD_TYPE=Release ..
          cmake --build build
